apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: {{ .Values.dataGeneration.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    notebooks.opendatahub.io/inject-auth: "true"
    notebooks.opendatahub.io/last-image-selection: "agent-mesh-data-generation:{{ .Values.version }}"
    opendatahub.io/workbench-image-namespace: {{ .Values.namespace }}
    opendatahub.io/image-display-name: Agent Mesh - Data Generation
    opendatahub.io/hardware-profile-name: default-profile
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
  labels:
    app: {{ .Values.dataGeneration.name }}
    opendatahub.io/odh-managed: "true"
    opendatahub.io/dashboard: "true"
spec:
  template:
    spec:
      {{- if .Values.repoUrl }}
      initContainers:
        - name: git-clone
          image: alpine/git
          command:
            - sh
            - -c
            - |
              git clone {{ .Values.repoUrl }} /opt/app-root/src &&
              cd /opt/app-root/src &&
              git checkout {{ .Values.repoRef }}
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: workbench-data-generation-pvc
      {{- end }}
      containers:
        - name: {{ .Values.dataGeneration.name }}
          image: "{{ .Values.registry }}/{{ .Values.dataGeneration.name }}:{{ .Values.version }}"
          resources:
            requests:
              cpu: {{ .Values.dataGeneration.resources.requests.cpu }}
              memory: {{ .Values.dataGeneration.resources.requests.memory }}
            limits:
              cpu: {{ .Values.dataGeneration.resources.limits.cpu }}
              memory: {{ .Values.dataGeneration.resources.limits.memory }}
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: workbench-data-generation-pvc
          envFrom:
            - secretRef:
                name: code-understanding-env
          env:
            - name: NOTEBOOK_ARGS
              value: >-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/{{ .Values.namespace }}/{{ .Values.dataGeneration.name }}
                --ServerApp.quit_button=False
            - name: JUPYTER_IMAGE
              value: "{{ .Values.registry }}/{{ .Values.dataGeneration.name }}:{{ .Values.version }}"
      volumes:
        - name: workbench-data-generation-pvc
          persistentVolumeClaim:
            claimName: workbench-data-generation-pvc
