---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-dspa-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.rootUser }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.rootPassword }}
---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: {{ .Values.namespace }}
spec:
  apiServer:
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    caBundleFileMountPath: ''
    caBundleFileName: ''
    cacheEnabled: false
    pipelineStore: database
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      host: minio-api-{{ .Values.namespace }}.{{ .Values.clusterDomain }}
      port: "443"
      scheme: https
      secure: true
      region: {{ .Values.minio.region }}
      bucket: {{ .Values.minio.bucket }}pipelines
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
