---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datagen-storage
  namespace: {{ .Values.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphrag-storage
  namespace: {{ .Values.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
